
import Head from 'next/head'
import Image from 'next/image'

import ReactHtmlParser, { processNodes, convertNodeToElement, htmlparser2 } from 'react-html-parser';


import styles from '../styles/Home.module.css'
import TableauEmbed from '../components/TableauEmbed'





export default function Home() {


  const html = "<div><div class=\'tableauPlaceholder\' id=\'viz1651165037078\' style=\'position: relative\'><noscript><a href=\'#\'><img alt=\'GESTIÓN DE METAS Y CONTRIBUCIÓN A LOS ODSSECRETARIA DE EDUCACIÓN \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;OD&#47;ODSEDUCACION&#47;Dashboard1&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /> <param name=\'embed_code_version\' value=\'3\' /> <param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'ODSEDUCACION&#47;Dashboard1\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;OD&#47;ODSEDUCACION&#47;Dashboard1&#47;1.png\' /> <param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'es-ES\' /><param name=\'filter\' value=\'publish=yes\' /></object></div>                <script type=\'text/javascript\'>                    var divElement = document.getElementById(\'viz1651165037078\');                    var vizElement = divElement.getElementsByTagName(\'object\')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width=\'1000px\';vizElement.style.height=\'827px\';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width=\'1000px\';vizElement.style.height=\'827px\';} else { vizElement.style.width=\'100%\';vizElement.style.height=\'1627px\';}                     var scriptElement = document.createElement(\'script\');                    scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script></div>";

  const thisIsMyCopy = '<p>copy copy copy <strong>strong copy</strong></p>';

  return (

    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.grafico}>
       
       <h1>Hola</h1>
       
       <div  dangerouslySetInnerHTML={{__html: html}} ></div>

       
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://public.tableau.com/views/EmergenciaVialAtencionHistoria/TotalEmergenciasporCondicin?:language=es-ES&:display_count=n&:origin=viz_share_link"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        


      </footer>
    </div>
  )
}
